In [10]:
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
#csv file path
transplant_data_file = "Data/Transplant___Transplant_Year_by_Recipient_Age_Organ.csv"

In [17]:
#import csv, read it and make a dataframe
transplant_data_raw = pd.read_csv(transplant_data_file)

In [18]:
#rename some columns
transplant_data_raw = transplant_data_raw.rename(columns={'Recipient Age': 'Recipient_Age', 
                                                          'Organ Type': 'Organ_Type', 'To Date': 'To_Date'})
transplant_data_raw

,Recipient_Age,Organ_Type,To_Date,2023,2022,2021,2020,2019,2018,2017,...,1997,1996,1995,1994,1993,1992,1991,1990,1989,1988
0,All Recipient Ages,All Organs,"935,973","14,890","42,889","41,356","39,036","39,719","36,530","34,770",...,"20,316","19,765","19,396","18,299","17,631","16,134","15,756","15,001","13,140","12,623"
1,All Recipient Ages,Kidney,"551,502","8,754","25,500","24,670","22,817","23,401","21,167","19,849",...,"11,710","11,411","11,084","10,646","10,360","9,738","9,678","9,416","8,656","8,878"
2,All Recipient Ages,Liver,"204,150","3,410","9,528","9,236","8,906","8,896","8,250","8,082",...,"4,189","4,087","3,934","3,652","3,440","3,064","2,953","2,690","2,202","1,713"
3,All Recipient Ages,Pancreas,"9,313",33,108,143,135,143,192,213,...,210,164,109,95,112,64,78,69,82,78
4,All Recipient Ages,Kidney / Pancreas,"27,340",265,810,820,827,872,835,789,...,852,861,919,748,661,493,452,459,335,171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,Unknown,All Organs,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
122,Unknown,Kidney,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
123,Unknown,Head & Neck: Larynx,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
124,Unknown,Upper Limb: Bilateral,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
125,Unknown,Upper Limb: Unilateral,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
#drop certain rows from transplant_data_raw from 'Recipient_Age' columns
rows_drop_list = ['Unknown']
transplant_data = transplant_data_raw[transplant_data_raw.Recipient_Age.isin(rows_drop_list) == False]
transplant_data

,Recipient_Age,Organ_Type,To_Date,2023,2022,2021,2020,2019,2018,2017,...,1997,1996,1995,1994,1993,1992,1991,1990,1989,1988
0,All Recipient Ages,All Organs,"935,973","14,890","42,889","41,356","39,036","39,719","36,530","34,770",...,"20,316","19,765","19,396","18,299","17,631","16,134","15,756","15,001","13,140","12,623"
1,All Recipient Ages,Kidney,"551,502","8,754","25,500","24,670","22,817","23,401","21,167","19,849",...,"11,710","11,411","11,084","10,646","10,360","9,738","9,678","9,416","8,656","8,878"
2,All Recipient Ages,Liver,"204,150","3,410","9,528","9,236","8,906","8,896","8,250","8,082",...,"4,189","4,087","3,934","3,652","3,440","3,064","2,953","2,690","2,202","1,713"
3,All Recipient Ages,Pancreas,"9,313",33,108,143,135,143,192,213,...,210,164,109,95,112,64,78,69,82,78
4,All Recipient Ages,Kidney / Pancreas,"27,340",265,810,820,827,872,835,789,...,852,861,919,748,661,493,452,459,335,171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,72 +,Heart / Lung,16,2,3,1,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0
117,73 +,Intestine,40,0,2,2,3,3,2,4,...,0,0,0,0,0,0,0,0,0,0
118,74 +,Head & Neck: Craniofacial,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
119,75 +,Upper Limb: Bilateral,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
120,76 +,Upper Limb: Unilateral,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
#find list of all organ transplant types
transplant_organ_complete = transplant_data.Organ_Type.unique()
transplant_organ_complete

array(['All Organs', 'Kidney', 'Liver', 'Pancreas', 'Kidney / Pancreas',
       'Heart', 'Lung', 'Heart / Lung', 'Intestine', 'Abdominal Wall',
       'Head & Neck: Craniofacial', 'Head & Neck: Scalp',
       'Head & Neck: Larynx', 'GU: Penile', 'GU: Uterus',
       'Upper Limb: Bilateral', 'Upper Limb: Unilateral', 'Trachea', nan],
      dtype=object)

In [21]:
#drop certain organ types from Organ_Type column
organs_drop_list = ['All Organs', 'Intestine', 'Abdominal Wall',
       'Head & Neck: Craniofacial', 'Head & Neck: Scalp',
       'Head & Neck: Larynx', 'GU: Penile', 'GU: Uterus',
       'Upper Limb: Bilateral', 'Upper Limb: Unilateral', 'Trachea']
transplant_data_new = transplant_data[transplant_data.Organ_Type.isin(organs_drop_list) == False]
transplant_data_new

,Recipient_Age,Organ_Type,To_Date,2023,2022,2021,2020,2019,2018,2017,...,1997,1996,1995,1994,1993,1992,1991,1990,1989,1988
1,All Recipient Ages,Kidney,"551,502","8,754","25,500","24,670","22,817","23,401","21,167","19,849",...,"11,710","11,411","11,084","10,646","10,360","9,738","9,678","9,416","8,656","8,878"
2,All Recipient Ages,Liver,"204,150","3,410","9,528","9,236","8,906","8,896","8,250","8,082",...,"4,189","4,087","3,934","3,652","3,440","3,064","2,953","2,690","2,202","1,713"
3,All Recipient Ages,Pancreas,"9,313",33,108,143,135,143,192,213,...,210,164,109,95,112,64,78,69,82,78
4,All Recipient Ages,Kidney / Pancreas,"27,340",265,810,820,827,872,835,789,...,852,861,919,748,661,493,452,459,335,171
5,All Recipient Ages,Heart,"88,908","1,417","4,111","3,818","3,658","3,552","3,408","3,244",...,"2,293","2,343","2,363","2,340","2,297","2,170","2,127","2,107","1,705","1,676"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,68 +,Pancreas,44,0,0,4,1,1,4,5,...,1,0,0,0,0,0,0,0,0,0
113,69 +,Kidney / Pancreas,63,5,2,3,7,4,8,6,...,0,0,0,0,0,0,0,0,0,0
114,70 +,Heart,"10,794",265,741,730,659,594,659,573,...,192,163,140,96,104,86,73,72,41,24
115,71 +,Lung,"11,473",367,"1,109",932,981,961,885,819,...,42,26,22,19,13,6,3,3,0,0
116,72 +,Heart / Lung,16,2,3,1,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0

In [22]:
#drop nan values
transplant_data_drop = transplant_data_new.dropna()
transplant_data_drop

,Recipient_Age,Organ_Type,To_Date,2023,2022,2021,2020,2019,2018,2017,...,1997,1996,1995,1994,1993,1992,1991,1990,1989,1988
1,All Recipient Ages,Kidney,"551,502","8,754","25,500","24,670","22,817","23,401","21,167","19,849",...,"11,710","11,411","11,084","10,646","10,360","9,738","9,678","9,416","8,656","8,878"
2,All Recipient Ages,Liver,"204,150","3,410","9,528","9,236","8,906","8,896","8,250","8,082",...,"4,189","4,087","3,934","3,652","3,440","3,064","2,953","2,690","2,202","1,713"
3,All Recipient Ages,Pancreas,"9,313",33,108,143,135,143,192,213,...,210,164,109,95,112,64,78,69,82,78
4,All Recipient Ages,Kidney / Pancreas,"27,340",265,810,820,827,872,835,789,...,852,861,919,748,661,493,452,459,335,171
5,All Recipient Ages,Heart,"88,908","1,417","4,111","3,818","3,658","3,552","3,408","3,244",...,"2,293","2,343","2,363","2,340","2,297","2,170","2,127","2,107","1,705","1,676"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,68 +,Pancreas,44,0,0,4,1,1,4,5,...,1,0,0,0,0,0,0,0,0,0
113,69 +,Kidney / Pancreas,63,5,2,3,7,4,8,6,...,0,0,0,0,0,0,0,0,0,0
114,70 +,Heart,"10,794",265,741,730,659,594,659,573,...,192,163,140,96,104,86,73,72,41,24
115,71 +,Lung,"11,473",367,"1,109",932,981,961,885,819,...,42,26,22,19,13,6,3,3,0,0
116,72 +,Heart / Lung,16,2,3,1,1,2,1,1,...,0,0,0,0,0,0,0,0,0,0

In [23]:
#get list of all recipient age groups
recipient_age_groups = transplant_data_drop.Recipient_Age.unique()
recipient_age_groups

array(['All Recipient Ages', '< 1 Year', '1-5 Years', '6-10 Years',
       '11-17 Years', '18-34 Years', '35-49 Years', '50-64 Years', '66 +',
       '67 +', '68 +', '69 +', '70 +', '71 +', '72 +'], dtype=object)

In [24]:
#gather just the pediatric data
pediatric_ages = ['< 1 Year', '1-5 Years', '6-10 Years',
       '11-17 Years']
transplant_data_peds = transplant_data_drop[transplant_data_drop['Recipient_Age'].isin(pediatric_ages)]
transplant_data_peds

,Recipient_Age,Organ_Type,To_Date,2023,2022,2021,2020,2019,2018,2017,...,1997,1996,1995,1994,1993,1992,1991,1990,1989,1988
19,< 1 Year,Kidney,117,0,1,0,0,0,0,0,...,3,7,7,4,6,4,10,8,6,8
20,< 1 Year,Liver,"5,322",39,145,139,139,155,154,133,...,169,154,114,157,118,135,145,144,122,87
21,< 1 Year,Pancreas,179,0,1,1,5,4,1,1,...,0,0,0,1,0,0,1,0,0,0
22,< 1 Year,Kidney / Pancreas,8,0,0,0,0,0,0,0,...,1,1,0,0,0,0,0,0,0,0
23,< 1 Year,Heart,"3,404",33,114,111,124,133,119,111,...,95,74,91,90,108,90,125,88,72,35
24,< 1 Year,Lung,124,1,1,5,7,4,2,3,...,6,7,9,5,2,0,2,0,1,0
25,< 1 Year,Heart / Lung,17,0,0,0,0,0,1,0,...,0,0,2,0,0,1,0,0,1,0
30,1-5 Years,Kidney,"5,244",60,148,184,184,164,167,183,...,132,139,112,93,145,121,120,116,118,119
31,1-5 Years,Liver,"7,221",68,170,186,166,205,214,249,...,211,195,198,230,220,192,198,191,200,170
32,1-5 Years,Pancreas,384,3,6,13,6,5,20,11,...,5,2,1,1,2,1,0,0,0,1
33,1-5 Years,Kidney / Pancreas,23,0,0,0,2,2,0,0,...,1,1,0,0,2,0,0,0,0,0
34,1-5 Years,Heart,"2,674",24,97,106,100,114,113,107,...,64,55,60,63,54,62,53,50,23,20
35,1-5 Years,Lung,152,0,3,2,3,4,1,4,...,7,3,8,3,5,6,5,2,0,0
36,1-5 Years,Heart / Lung,54,0,0,1,0,1,1,0,...,3,5,1,5,7,3,2,3,1,2
40,6-10 Years,Kidney,"5,003",57,122,138,129,156,160,131,...,137,146,147,140,135,122,163,146,146,123
41,6-10 Years,Liver,"2,670",25,67,63,64,89,76,83,...,73,74,84,72,85,64,70,69,61,70
42,6-10 Years,Pancreas,96,1,1,4,3,7,7,9,...,2,1,0,0,2,0,0,0,0,0
43,6-10 Years,Kidney / Pancreas,18,0,1,1,1,0,1,1,...,1,0,0,0,0,0,0,0,0,0
44,6-10 Years,Heart,"1,626",19,66,67,67,80,67,48,...,37,38,42,38,33,23,20,23,17,19
45,6-10 Years,Lung,232,2,1,4,3,5,7,5,...,13,7,8,6,7,9,6,1,1,0
46,6-10 Years,Heart / Lung,30,0,0,0,0,0,0,0,...,2,1,2,3,0,1,2,0,3,3
51,11-17 Years,Kidney,"15,482",122,432,497,397,440,428,432,...,405,417,454,436,376,344,348,372,366,407
53,11-17 Years,Liver,"4,047",39,144,113,133,102,119,134,...,119,111,110,94,99,104,88,108,71,81
54,11-17 Years,Pancreas,89,0,4,2,4,2,3,8,...,2,1,0,1,0,1,0,2,0,0
55,11-17 Years,Kidney / Pancreas,25,0,1,0,2,1,0,1,...,0,0,2,1,0,0,0,2,0,0
56,11-17 Years,Heart,"4,044",75,214,204,170,180,169,165,...,81,95,79,72,77,59,63,59,41,44
57,11-17 Years,Lung,959,9,13,12,19,37,25,32,...,35,31,42,17,22,22,20,6,1,1
58,11-17 Years,Heart / Lung,115,0,3,1,4,1,3,1,...,0,4,7,7,7,5,6,3,2,6

In [25]:
#calculate years to adulthood. Create variable calculations. Under a year is +18, 1-5 is +17, 6-10 is +12, 
transplant_data_peds.to_csv('file_name.csv')